"""Qt-independent domain models and policies."""

from mpv_enhancer.domain.models import Playlist, QueueItem
from mpv_enhancer.domain.presets import (
    STARTER_PRESETS,
    PresetKey,
    SettingsPreset,
)
from mpv_enhancer.domain.selection_settings import (
    SelectedSettingState,
    SelectedSettingValue,
    SettingPatch,
    apply_selection_patch,
    inspect_selected_setting,
    reset_all_selection_overrides,
    reset_selection_setting,
)
from mpv_enhancer.domain.settings import (
    DETERMINISTIC_BASELINE,
    EMPTY_PLAYBACK_SETTINGS,
    SETTING_SPEC_REGISTRY,
    AspectRatio,
    AspectRatioMode,
    EffectivePlaybackSettings,
    EffectiveSettingsResolver,
    LanguagePreferences,
    PlaybackSettings,
    SettingKey,
    SettingSpec,
    SettingSpecRegistry,
    SettingValue,
    SettingValueType,
    TrackSelection,
    TrackSelectionMode,
)
from mpv_enhancer.domain.validation import (
    DEFAULT_SUPPORTED_MEDIA_EXTENSIONS,
    SUPPORTED_MEDIA_POLICY,
    SupportedExtensionPolicy,
    is_supported_media_path,
)

__all__ = [
    "AspectRatio",
    "AspectRatioMode",
    "DEFAULT_SUPPORTED_MEDIA_EXTENSIONS",
    "DETERMINISTIC_BASELINE",
    "EMPTY_PLAYBACK_SETTINGS",
    "SUPPORTED_MEDIA_POLICY",
    "SETTING_SPEC_REGISTRY",
    "EffectivePlaybackSettings",
    "EffectiveSettingsResolver",
    "LanguagePreferences",
    "Playlist",
    "PlaybackSettings",
    "PresetKey",
    "QueueItem",
    "SelectedSettingState",
    "SelectedSettingValue",
    "SettingKey",
    "SettingPatch",
    "SettingSpec",
    "SettingSpecRegistry",
    "SettingValue",
    "SettingValueType",
    "SettingsPreset",
    "STARTER_PRESETS",
    "TrackSelection",
    "TrackSelectionMode",
    "SupportedExtensionPolicy",
    "apply_selection_patch",
    "inspect_selected_setting",
    "is_supported_media_path",
    "reset_all_selection_overrides",
    "reset_selection_setting",
]
